### ISSUE TITLE
User is not able to listen to events inside room

### ISSUE THREAD

**Issue by chiragpurohit71085** [AppSaloon/socket.io-tester#5]
I have connected user in the room and added event in the Listen for events.

However I am not able to get any events for this.
(i.e events that are broadcasted or fired for particular room using io.to)

eg.

io.to('store_123').emit('uploadmedia',result_data);

**Comment by Cinezaster** [comment]
We have not tested support for rooms, we did implement and tested namespaces.

We are currently developing an electron app because google is going to stop supporting chrome apps. We're developing in the electron branch.

How would you suggest we could implement support for rooms. 
Since we add "/namespace" in the url we could use "#room" to join a room?

**Comment by Cinezaster** [comment]
#6 I added this to our feature list

**Comment by chiragpurohit71085** [comment]
Hi

Thanks...

**Comment by JoJordens** [comment]
While this always should've worked, it has now been tested and confirmed to be working in the latest version.

**Comment by chiragpurohit71085** [comment]
Hi

Thanks.
